[certificate]
# Title color in HTML format
color = "000066"
# Title of the conference, long style
title_long = "Workshop ``Climate Change and Insurance'' -- CCI 2026"
# Description of the venue(s) where the conference was held
place = "with the first two days at the IE Campus in Segovia, Spain, and the final day at the IE Tower in Madrid, Spain"
# Time range of the conference
duration = "2--4 September 2026"
# Name of the conference's host, the one giving out these certificates
host = "Prof. David Gómez-Ullate"
# Main logo of the conference
path_logo_conference = "./img/ie_scitech_logo.png"
# Additional logos, must be a list of paths
# path_logo_organizers = ["./img/ucadatalab.png", "./img/ucadatalab.png"]
# Signature of the host (recommended png format with transparency)
path_signature = "./img/signature.png"
