[certificate]
color = "b71a3b"  # HTML format
title_short = "Symmetries, Invariants, and their Applications"
title_long = "Symmetries, Invariants, and their Applications"
place = "University of Dalhousie"
duration = "from 3rd to 5th August, 2022"
host = "Prof. Dr. Robert Milson"
path_logo_conference = "./img/dalhousie.jpg"
path_logo_organizers = []  # Must be a list of paths
path_signature = "./img/signature.png"
